#!/usr/bin/env python3
"""
A simple script to convert FlightRadar24 data into SQL requests for our model database
"""

import csv
import argparse

# Parse arguments
parser = argparse.ArgumentParser()
parser.add_argument('files', action='append', nargs='+', help='FlightRadar24 CSV files to use as input')
parser.add_argument('-o', help='Output file name', default='fr24data.sql')
args = parser.parse_args()
input_files = args.files[0]

# Resulting SQL entries
entries = []

# Parse CSV files
for file in input_files:
    with open(file, 'r') as filedesc:
        csvfile = csv.DictReader(filedesc)
        for row in csvfile:
            position = []
            position.extend(row['Position'].split(','))
            position.append('{:.6f}'.format(round((float(row['Altitude']) * 0.3048) / (1000 * 111), 6)))
            timestamp = row['UTC'].replace('T', ' ').replace('Z', '')
            entry = (
                ' '.join(position),
                row['Direction'] + 'ртр',
                timestamp,
                row['Callsign']
            )
            entries.append(entry)

with open(args.o, 'w') as file:
    print('-- Autogenerated file with FlightRadar24 data', file=file)
    print('SET search_path TO cc,public;', file=file)
    print('', file=file)
    for entry in entries:
        print('INSERT INTO radar_data(coordinates, source, captured, data) VALUES (\'POINT({})\', \'{}\', \'{}\', \'{}\');'.format(entry[0], entry[1], entry[2], entry[3]), file=file)
